### ISSUE TITLE
Validator rewards post-merge

### ISSUE THREAD

**Issue by bertmiller** [flashbots/flashbots-data-transparency#6]
Some important stakeholders have asked me for an updated estimate of how much MEV will increase rewards post-merge. They'd like an expected breakdown between how much rewards to expect between:
- inflation
- priority fee tips
- MEV

We've done this work once already in Alex's MEV in ETH2.0 (I believe @taarushv contributed the data for that), but an updated metric would be important for those looking to offer products that encourage others to stake with them, and which enable Flashbots on that stake.

**Comment by come-maiz** [comment]
Here is the early exploration by @taarushv and @obadiaa:
https://writings.flashbots.net/research/mev-eth2/

**Comment by elenahoo** [comment]
To update and improve the previous [MEV in ETH2](https://hackmd.io/@flashbots/mev-in-eth2) analysis, the following factors need to be considered:

- ETH burned post EIP-1559
- Dynamic MEV (rather than a fixed MEV)
- Participation rate range update
- Increasing number of validators

### ETH Burned
Based on observed historical data of ETH burned (Base Fee * Gas Used), the burned amount per block can be estimated using:

- A constant number as approximation due to its stationary behaviour described in https://github.com/ethereum/abm1559
- A mean-reverting and momentum time-series model to account for the stickiness of monotonically increasing/decreasing short-term trend and the mean-reverting stationary long-term trend

### Dynamic MEV Prediction
MEV can be predicted as a class or as a continuous variable. A multi-factor model with a categorical target variable or a continuous target variable can include multiple features i.e. base fee, gas price, eth price, previous block MEV etc. to see if these factors are useful in predicting MEV. The following methods explore how MEV can be predicted as a class by classification models and by Markov chain as a probabilistic event through state transition; and how MEV can be predicted  as a continuous variable through time-series models.

#### Predict MEV as a class

1. Split MEV per block into different buckets i.e. MEV < 10ETH, 10<=MEV<=20ETH, MEV>20ETH. The bucket boundaries can be determined from clustering methods.
2. This turns the prediction into a classification problem, so one can use typical classification models like decision tree, SVM, KNN, Random Forest, Neural Network etc. to predict the MEV buckets.

#### Predict MEV as a continuous variable

1. Since there’s a time dependent factor here where the previous block's MEV could significantly affect the current block's MEV, it’s reasonable to consider time-series models like autoregressive models
2. Some simple models to try could be AR(n) or ARMA(n), the time steps will need to be constant for these models to work. So using timestamp rather than block number to organise the data is a better approach (i.e. use MEV per second rather than MEV per block).
3. Some more advanced models to try could be a combination of mean-reversion and momentum components in the time-series model set-up. The momentum component captures the short-term monotonicity in MEV whereas the mean-reversion component captures the long-term effect of reverting back to a normal MEV after an extremely large (or small) MEV.

#### Predict MEV as a state transition

1. Use stochastic models such as the Markov chain to describe MEV as a sequence of possible states (high, average, low MEV, or more granular states) in which the probability of each state depends only on the state attained in the previous state. Then construct a transition matrix with each state for each time step to predict the conditional probability of transitioning into a specific state in the next time step given the current state.
2. The downside of this approach is that it'll be computationally expensive and might be too difficult to run in practice given the number of states and the high frequency time steps.
3. Alternatively, neural-network can also be considered to model state transition, using each neural layer as a sate and each perceptron within a layer as a possible outcome. This will resolve the computational concerns because the deep learning space is well developed and can run pretty fast.

### Participation Rate
Previously a series of participation rates were considered in the simulation i.e. 100%, 99%, 98%, 97%, 96%. We'd like to assess whether these rates are still feasible post-merge and whether a wider range of values should be considered.

### # of Validators
This has increased significantly since our last analysis. We'd like to update the range of simulated number of validators and the upper bound of the ETH staked to reflect this increase.

**Comment by elenahoo** [comment]
Issue raised  https://github.com/flashbots/eth2-research/issues/4#issue-1311601836 related to the existing work and data collection for the update analysis.

**Comment by elenahoo** [comment]
Next step based on brainstorming session:
- [x] Update the analysis latest data post London fork
- [x] Use a fixed REV in the first version to get return difference between using FB bundle vs. not using FB bundle
- [x] Change fixed REV to a dynamic REV through modeling (Aug 31, 2022)
- [x] Improve the analysis based on a dynamic REV (Sep 30, 2022)

**Comment by come-maiz** [comment]
@elenahoo are all those next steps done?

**Comment by elenahoo** [comment]
I added the status above. The first two are done. I'm working on the other two.

**Comment by come-maiz** [comment]
Thanks. You can use: 

- [x] this kind of lists
- [ ] lists

And for tasks that will take more than a little while, you can link the item in the list to more details about the task.

**Comment by elenahoo** [comment]
Tasks all completed and article published on [discourse](https://collective.flashbots.net/t/modelling-realised-extractable-value-in-proof-of-stake-ethereum/290)
